aneoconsulting/ArmoniK.CLI

.github/workflows/publish.yaml, mypy.ini, pyproject.toml, setup.py
The project workflow dedicated to publishing test versions on test.pypi.org fails when a pull request is updated without adding new commits to the previous ones.
This change fixes this issue by generating a unique version each time the pipeline is run. This solution is a work around that uses setup.py. This is not ideal and a better solution should be implemented when possible. For more details on the reasons for this change, see:
* this stack overflow [thread](https://stackoverflow.com/questions/73605607/how-to-use-setuptools-scm) on the limitations of setuptools_scm.
* this [page](https://setuptools-scm.readthedocs.io/en/latest/customizing/) in the setuptools-scm documentation describing how to customize a version.
Tested using the CI.
Project test versions are available on …
=> fix: publication to PyPiTest

src/armonik_cli/cli.py, tests/commands/test_sessions.py, tests/test_cli.py
Add the short flag "-h" to display help message on all commands.
Update CLI configuration to add the short help flag.
Unit tests updated.
No impact, this modification maintains backward compatibility.
No.
=> feat: add short help option

pyproject.toml, src/armonik_cli/commands/sessions.py, src/armonik_cli/core/__init__.py, src/armonik_cli/core/filter_grammar.lark, src/armonik_cli/core/filters.py, src/armonik_cli/core/params.py, src/armonik_cli/utils.py, tests/core/test_filters.py, tests/core/test_params.py, tests/test_utils.py
The current version of the CLI does not provide filtering support for list queries.
The implemented solution uses a custom parser built from a grammar adapted to the filter description. The parser constructs an AST, which is then traversed and transformed into a filter. This logic is then encapsulated in a custom Click parmeter type.
A large number of unit tests have been added to validate the implementation.
Modifications are fully backward-compatible.
No.
=> feat: add filter support in command-line arguments

src/armonik_cli/cli.py, src/armonik_cli/commands/__init__.py, src/armonik_cli/commands/partitions.py, src/armonik_cli/core/console.py, src/armonik_cli/core/serialize.py, tests/commands/test_partitions.py
The current version of the CLI doesn't have partition-specific commands.
Added commands for : 
- Listing partitions
- Getting partitions
Unit tests for the serialization and commandline argument parsing.
Will be in draft until Tasks is merged (for sorting)
=> feat: Added partition commands

src/armonik_cli/commands/partitions.py, src/armonik_cli/commands/sessions.py, src/armonik_cli/commands/tasks.py
Adopted a new standard where functions implementing command `command` are prefixed by the group (`group_command`) to avoid overriding Python's builtin functions (such as "list" or "set") as that can cause unexpected behavior.
- Changed the names of the different functions 
- Changed condition on Tasks list command 
Code refactor, all tests still pass.
Have to reinforce the naming standard.
None.
=> refactor: changed names of functions to avoid overriding builtins

src/armonik_cli/commands/sessions.py
Session's list command didn't have support for the sort and page options.
Added support for `--sort-*` and `--page*` options to the sessions' list command.
- Tested sorting locally.
- Unit tests pass.
Would impact the documentation if it existed.
None.
=> fix: Added support for sort and page options to sessions' list command 

src/armonik_cli/commands/tasks.py, tests/commands/test_tasks.py
Filters already allow you to specify session_id, moreover, we can imagine use cases where you might want to list all tasks regardless of what session they belong to (all tasks that have failed).
- Removed session-id as a parameter from `task list`
Changed unit tests, tests pass locally and in CI
None.
=> fix: session-id is no longer a required argument for task list command

pyproject.toml, src/armonik_cli/cli.py, src/armonik_cli/commands/partitions.py, src/armonik_cli/commands/sessions.py, src/armonik_cli/commands/tasks.py, src/armonik_cli/core/__init__.py, src/armonik_cli/core/common.py, src/armonik_cli/core/decorators.py, src/armonik_cli/core/options.py, tests/core/test_decorators.py, tests/core/test_options.py
In the current version of the CLI, all commands share common options, namely : --endpoint, --output and --debug. These options can only be passed after the last command. It would be preferable to be able to pass them at any level of the command hierarchy, to simplify the entry of new commands with identical values for some or all of these options.
For example, the three following commands should be allowed and work identically.
`armonik --endpoint <endpoint> session list`
`armonik session --endpoint <endpoint> list`
`armonik session list --endpoint <endpoint>`
Implements a custom option type called GlobalOption supporting value passing at any level of the command hierarchy, as well as a base_group decorator to add common options to all command groups easily.
Manually tested and unit tests …
=> feat: add global option support

src/armonik_cli/commands/tasks.py, src/armonik_cli/core/decorators.py, src/armonik_cli/exceptions.py, tests/commands/test_tasks.py, tests/core/test_decorators.py
The error handler would capture all error messages and obfuscate them.
Rewrote the error handler so that it prints out the error details in a neater way (using click/rich_click) and such that the debug option allows you to view said error
Generated different gRPC errors and observed the error messages generated.
None.
None.
=> fix: Improved error message clarity

src/armonik_cli/commands/tasks.py, tests/commands/test_tasks.py, tests/conftest.py
`task create` would return a list with a single task object
- `task create` now returns a singular task object instead
- changed the return type of `reformat_cmd_output` from `str` to `Union[str, Dict[str, Any]]`
Unit tests pass but it uses the new error handler which produces click errors (which obfuscate exit codes..) 
Small improvements towards a better and more consistent tool. 
None.
=> fix: task create now returns a single task object

src/armonik_cli/cli.py, src/armonik_cli/commands/__init__.py, src/armonik_cli/commands/results.py, src/armonik_cli/core/__init__.py, src/armonik_cli/core/options.py, src/armonik_cli/core/params.py, src/armonik_cli/core/serialize.py, tests/commands/test_results.py, tests/conftest.py, tests/core/test_options.py, tests/core/test_params.py
The current version of the CLI doesn't have result-specific commands.
Added commands for : 
- Listing results
- Getting details about results
- Creating results
- Deleting result data
- Uploading data to results
Along with a parameter type for parsing result inputs.
Unit testing for different failing scenarios, serialization and commandline argument parsing.
None.
=> feat: Added result commands

docs/Makefile, docs/armonik_core.rst, docs/cli_reference.rst, docs/conf.py, docs/development.rst, docs/index.rst, docs/installation.rst, docs/make.bat, docs/usage.rst, pyproject.toml
Need for a documentation site to serve as the foundation. Ideally, we need to set it up at this point so it can "force" as internally  to incrementally update and build upon said documentation  with each new PR.
Built upon @qdelamea-aneo's previous configuration in `qd/docs` as well as my initial PR ( #37 ) on documentation which used MkDocs. The choice of going with Sphinx made more sense because it's also being used in other ArmoniK projects. 
Added a "Getting Started" for both users and developers as well as a general installation guide, as well as hot reloading/local serving with sphinx-autobuild. 
Not applicable. 
Pipelines to automatically build and publish the documentation aren't in place yet. Another question for the future is potentially setting up "standards" …
=> docs: Added documentation

src/armonik_cli/commands/sessions.py, tests/commands/test_sessions.py
Other get commands for the CLI support multiple ids, it makes sense to homogonize them.
`session get` now supports multiple ids.
Unit tests pass.
None.
@qdelamea-aneo With the nature of sessions being a less prevalent entity in ArmoniK in comparison to tasks and results, it feels to me like it wouldn't make sense to allow the user to cancel or delete multiple sessions at once. There is no "performance benefit" to it too since the session commands only take in one argument. What do you think ?
=> feat: session get command now supports multiple ids

src/armonik_cli/cli.py
In the command help messages, all the options are grouped together and the alphabetical order is not respected. Some options, however, are global and should be distinguished from command-specific options.
Added command groups that divide options into three groups in help messages: common options (e.g. --output, --debug, etc.), cluster configuration options (e.g. --endpoint, etc) and command-specific options. Within a group, options are listed in alphabetical order.
No unit tests. As the result is visual, it has been manually validated.
* Future global options must be added to the corresponding option group.
* If future commands have no global options (or only a subset), the behavior implemented here will have to be adapted.
* Styling effects can be added to groups, but are …
=> feat: Added option groups

src/armonik_cli/core/filters.py, src/armonik_cli/core/params.py
The error messages displayed for some invalid filter expressions are obscure. These are expressions that do not respect the grammar and therefore cause an error during parsing.
Added a new exception for parsing errors and an additional logic to intercept parsing issues and infer the reason to display a clear message.
Unit tests still pass.
No impact.
Error messages are inferred from examples to best describe the situation causing the error. These examples should be completed over time to provide the most appropriate error messages for each situation.
=> fix: Filter parameter parsing error messages

src/armonik_cli/commands/cluster.py, src/armonik_cli/commands/partitions.py, src/armonik_cli/commands/results.py, src/armonik_cli/commands/sessions.py, src/armonik_cli/commands/tasks.py, src/armonik_cli/core/common.py, src/armonik_cli/core/configuration.py, src/armonik_cli/core/decorators.py, tests/commands/test_partitions.py, tests/commands/test_results.py, tests/commands/test_sessions.py, tests/commands/test_tasks.py
Added CLI configuration in the previous PR but the commands still rely on getting everything from the CLI parameters
Made small changes to all the commands so they use the CliConfig instead
Some changes had to be made to some unit tests, but they're all passing.
Documentation needs to be modified for the PR to be merged, specifically going over how configs work.
=> refactor: changes so all commands use config

src/armonik_cli/cli.py, src/armonik_cli/commands/cluster.py, src/armonik_cli/commands/config.py, src/armonik_cli/commands/partitions.py, src/armonik_cli/commands/results.py, src/armonik_cli/commands/sessions.py, src/armonik_cli/commands/tasks.py, src/armonik_cli/core/configuration.py, src/armonik_cli/core/decorators.py, src/armonik_cli/core/logging.py, tests/commands/test_partitions.py, tests/commands/test_results.py, tests/commands/test_tasks.py, tests/conftest.py
Need for a way to collect, store and properly display ArmoniK CLI logs without using print/echo.
- Added a class for logging into the terminal or file.
- Changed some prints over to logging
- Fixed a bug where group level commands get treated as defaults ([click issue](https://github.com/pallets/click/issues/2753))
Nothing significant that needs to be tested. It's basically a simple wrapper around a basic Python object. Moreover,
the stderr output direction clearly works because previous tests are passing (Warnings go to stderr by default).
=> feat: Added logging

src/armonik_cli/core/configuration.py, src/armonik_cli/core/decorators.py
Needed an easy way to overlay the automatically generated CLI configuration.
- Added the missing environment variable (AKCONFIG) for the additional config file
- Workaround for client-side peer name verification for TLS.
All previous tests pass.
=> fix: Missing environment variable config and TLS fix

setup.py
The version number generated for a release contains the string '“.dev<run-id>”.
Correct the version number generation script.
=> fix: Hook generating the project version

docs/Makefile, docs/api/armonik_cli.core.rst, docs/api/armonik_cli.rst, docs/api/index.rst, docs/api/modules.rst, docs/conf.py, docs/index.rst, src/armonik_cli/core/configuration.py
- Added missing API docs generation to the Makefile
- removed superfluous conditions for `create_grpc_channel`.
All previous tests pass.
=> fix: API doc generation missing and TLS condition

src/armonik_cli/commands/sessions.py
You need to pass in certain task options when creating sessions, I think we can just use reasonable defaults and leave it to the user to specify if needed. This closes #84 
Added default values for task options
Not Applicable.
This goes against the API's behavior, but this is "to be discussed"
=> feat: session creation defaults
